services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dpark_app
    restart: unless-stopped
    working_dir: /var/www
    command: php artisan serve --host=0.0.0.0 --port=8000
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
    env_file:
      - .env